SRC += drivers/actuators/motion/motion.c
SRC += drivers/actuators/mosfet_switches/mosfet_switches.c
SRC += drivers/actuators/ax12/ax12.c
SRC += drivers/actuators/dc_motor/dc_motor.c
SRC += drivers/actuators/analog_servo/analog_servo.c
SRC += drivers/sensors/colour/colour.c
SRC += drivers/sensors/optical/optical.c
