include $(SRCDIR)drivers/actuators/ax12/Makefile
include $(SRCDIR)drivers/actuators/motion/Makefile
include $(SRCDIR)drivers/actuators/analog_servo/Makefile
include $(SRCDIR)drivers/actuators/mosfet_switches/Makefile
