SRC += $(SRCDIR)initialisation/adc_config.c
SRC += $(SRCDIR)initialisation/clock_config.c
SRC += $(SRCDIR)initialisation/gpio_config.c
SRC += $(SRCDIR)initialisation/timer_config.c
SRC += $(SRCDIR)initialisation/uart_config.c
