SRC += tasks/task_test_1.c
SRC += tasks/task_test_2.c
SRC += tasks/task_blinky_led.c
SRC += tasks/task_roll_me_up.c
SRC += tasks/let_me_pass.c
SRC += tasks/idle.c
SRC += tasks/tasks_init.c
SRC += tasks/time_update.c
