SRC += executors/revolver/revolver.c
SRC += executors/door/door.c
SRC += executors/trunk/trunk.c
SRC += executors/colour_shifter/colour_shifter.c
SRC += executors/front_rollers/front_rollers.c
SRC += executors/rocket/rocket.c
