include $(SRCDIR)executors/trunk/Makefile
include $(SRCDIR)executors/revolver/Makefile
include $(SRCDIR)executors/door/Makefile
include $(SRCDIR)executors/front_rollers/Makefile
include $(SRCDIR)executors/colour_shifter/Makefile
