SRC += $(SRCDIR)main.c

include $(SRCDIR)Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS/Makefile
include $(SRCDIR)libs/STM32F4xx_HAL_Driver/Src/Makefile
include $(SRCDIR)Middlewares/Third_Party/FreeRTOS/Source/Makefile
include $(SRCDIR)libs/CMSIS/Device/ST/STM32F4xx/Source/Templates/Makefile
