include $(SRCDIR)/Middlewares/Makefile
include $(SRCDIR)/core/Makefile
include $(SRCDIR)/drivers/Makefile
include $(SRCDIR)/executors/Makefile
include $(SRCDIR)/initialisation/Makefile
include $(SRCDIR)/libs/Makefile
include $(SRCDIR)/tasks/Makefile
include $(SRCDIR)/utils/Makefile

SRC += main.c
